[build]
builder = "dockerfile"
dockerfilePath = "packages/DataScraper/service/Dockerfile"

[deploy]
# Use CMD from Dockerfile
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
