[build]
builder = "dockerfile"
dockerfilePath = "packages/DataScraper/service/Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
